### ISSUE TITLE
feature request: please add vm-name

### ISSUE THREAD

**Issue by devZer0** [henry-spanka/iomonitor#1]
i like this tool very - but why not showing the VM name besides VM id ? that would make things much easier, as you won't need extra step to identify virtual machine

**Comment by henry-spanka** [comment]
I agree with you. You can submit a pull request if you like.

**Comment by FreshXOpenSource** [comment]
feature is part of my pull request ;-)

**Comment by henry-spanka** [comment]
Thank you. Sorry for the delay lol. I have merged it now.

**Comment by devZer0** [comment]
thank you
